package items

import (
	plib "github.com/ywwg/packingdb/pkg/packinglib"
)

var campStuff = []*plib.Item{
	plib.NewItem("windshield sun shade", []string{"Camping"}, nil),
	plib.NewItem("tent", []string{"Camping"}, nil),
	plib.NewItem("sleeping bag", []string{"Camping"}, nil),
	plib.NewItem("camping cot", []string{"Camping"}, nil),
	plib.NewItem("wool blanket", []string{"Camping"}, nil).TemperatureRange(0, 44),
	plib.NewItem("2 pillow cases", []string{"Camping"}, nil),
	plib.NewItem("tent light", []string{"Camping"}, nil),
	plib.NewItem("headlamp", []string{"Dark", "Hiking"}, nil),
	plib.NewItem("towel for butt driving home", []string{"Burn"}, nil),
	plib.NewItem("tarps", []string{"Burn", "Quill Hill", "Tarping"}, nil),
	plib.NewItem("pool pole", []string{"Burn", "Tarping"}, nil),
	plib.NewItem("ropes", []string{"Burn", "Tarping"}, nil),
	plib.NewItem("bungies", []string{"Burn", "Tarping"}, nil),
	plib.NewItem("gaff tape", []string{"Burn", "Tarping"}, nil),
	plib.NewItem("sharpie", []string{"Burn", "Tarping"}, nil),
	plib.NewItem("shims", []string{"Burn", "Tarping"}, nil),
	plib.NewItem("2x battery string lights", []string{"Burn", "Con"}, nil),
	plib.NewItem("camp chair", []string{"Camping"}, nil),
	plib.NewItem("small camp table", []string{"Camping"}, nil),
	plib.NewItem("4x8 camp table", []string{"Burn"}, nil),
	plib.NewItem("camp stove", []string{"GrumpCamping"}, []string{"NoFire"}),
	plib.NewItem("propane", []string{"GrumpCamping"}, []string{"NoFire"}),
	plib.NewItem("saucepan", []string{"GrumpCamping"}, nil),
	plib.NewItem("frying pan", []string{"GrumpCamping"}, nil),
	plib.NewItem("1 box hot hands", []string{"Camping"}, nil).TemperatureRange(0, 45),
	plib.NewItem("camp plateware", []string{"Camping"}, nil),
	plib.NewItem("A CUP", []string{"Burn", "Camping"}, nil),
	plib.NewItem("multitool", []string{"Camping", "Hiking"}, nil),
	plib.NewItem("lighter/matches", []string{"Camping"}, []string{"NoFire"}),
	plib.NewItem("bug spray", []string{"Camping", "Hiking"}, nil),
	plib.NewItem("paper towels", []string{"Camping"}, nil).Consumable(0.25, "rolls"),
	plib.NewItem("trash bag", []string{"Camping"}, nil).Consumable(0.25, plib.NoUnits),
	plib.NewItem("recycle bag", []string{"Camping", "Tiny House"}, nil).Consumable(0.125, plib.NoUnits),
	plib.NewItem("camelbak", []string{"Burn", "Camping", "Hiking"}, nil),
	plib.NewItem("extra camelbak bite valves", []string{"Burn", "Camping"}, nil),
	plib.NewItem("cart", []string{"Burn"}, nil),
	plib.NewItem("towel", []string{"Camping", "Tiny House"}, nil),
	plib.NewItem("2x configured radios", []string{"Burn"}, nil),
	plib.NewItem("pencils", []string{"Burn"}, nil),
	plib.NewItem("gear ties", []string{"Burn", "Tarping"}, nil),
	plib.NewItem("first aid kit", []string{"Hiking"}, nil),
	plib.NewItem("sheet set", []string{"Tiny House"}, nil),
	plib.NewItem("hammock", []string{"Burn", "Camping"}, nil),
}
